


geo_vars <- c(
  "OMRÅDE",
  "HOVEDDELE",
  "BYER",
  "KOMK",
  "OER",
  "PNR20", # Postal code
  "SOGN",
  "KOMGRP",
  "REGLAND",
  "KOMMUNEDK",
  "LANDSDEL",
  "OMR20",
  "AMT",
  "BEBO",
  "REGION",
  "BOPREG",
  "BOP",
  "PROVSTI",
  "BOPKOM",
  "BOPOMR",
  "LONGRP",
  "BOPLANDK",
  "BOPKOMGRP",
  "KMDR",
  "LANDDEL"
)

# c(
#   "AKTOER",
#   "FINANSKILDE1",
#   "FINANSKILDE",
#   "MODSEKTOR",
#   "LAND",
#   "RESTANCE",
#   "DELTYP",
#   "BRUTNETUDG",
#   "FUNK1",
#   "DRANST",
#   "ART",
#   "GRUPPERING",
#   "DRANST1",
#   "REGI07A",
#   "REGI07",
#   "TVGRP",
#   "NATGRUP",
#   "SKATPCT",
#   "INDKOMST",
#   "SKATGRL",
#   "SKATPRO",
#   "SKAT",
#   "INDSKAT",
#   "POST",
#   "INDUDBOP",
#   "UHBEGREB",
#   "INDUD",
#   "BALANC",
#   "INDSEK",
#   "VALUTA",
#   "VIRKSTRRDA",
#   "EJERSKAB",
#   "HOVBRAN",
#   "KONC",
#   "PLAND",
#   "HANDEL",
#   "LANDGRP",
#   "VARE",
#   "DATAKILDE",
#   "SITC",
#   "INDEKSTYPE",
#   "SAESON2",
#   "NATION",
#   "DATA",
#   "UDSEK",
#   "INSTRNAT",
#   "RETNAT",
#   "UDLBRANCHE",
#   "INDLBRANCHE",
#   "VAREGR",
#   "HOVED",
#   "VARGR",
#   "BAGOPL",
#   "HUSSTAND",
#   "SAMIND",
#   "BOLFORM",
#   "EJENDOMSKATE",
#   "EJKAT20",
#   "OVERDRAG",
#   "VURDERING",
#   "URBANGRAD",
#   "UDGTYP",
#   "KURTYP",
#   "OPGOER",
#   "UDINDLÅN",
#   "LØBETID1",
#   "RENTFIX1",
#   "LAANSTR",
#   "RENTFIX",
#   "LAANSTRREPO",
#   "INSTITYPE",
#   "PAPIR",
#   "KUPON",
#   "LØBETID",
#   "UDSTEDSEKTOR",
#   "INVSEKTOR",
#   "VÆRDIAN",
#   "TYPREAL",
#   "LØBETID3",
#   "LØBETID2",
#   "KUPON2",
#   "UDSTED",
#   "DAEKOBL",
#   "DATAT",
#   "ISNINAVN",
#   "UDSTEDBRANC",
#   "HOLBRANC",
#   "ISIN",
#   "UAKT",
#   "OPT",
#   "HOVED1",
#   "KUPON1",
#   "UDSTLAND",
#   "INVESTOR",
#   "INVEST1",
#   "UDSTLAND2",
#   "UDLKAT",
#   "VAERDI1",
#   "INVESTLAND",
#   "TRANSAKT1",
#   "DIMENSION",
#   "KORTYPE",
#   "PRIVATERHVERV",
#   "KORTTEK",
#   "MISBRUG2",
#   "ANVSTED",
#   "KORTUDSTED",
#   "ENHED1",
#   "HAEVIND",
#   "BETJEN",
#   "RET",
#   "GEODAEK",
#   "KREDIT",
#   "INIT",
#   "VISITATION",
#   "YDTYPDETAL",
#   "HERKOMST1",
#   "BERET",
#   "MORUD",
#   "FARUD",
#   "DAGPENGERET",
#   "EKSISTENS",
#   "UDDKOMB",
#   "SOCIALSTATUS",
#   "UGER",
#   "BARNFAM",
#   "FORAELDREDAGPENGE",
#   "MORUDD",
#   "FARUDD",
#   "FORAELDREUDD",
#   "MODTAG1",
#   "PENSIONSTATUS",
#   "LTIMER",
#   "FORAN",
#   "ANBRINGELSE",
#   "ADMKOM",
#   "ANBRINGAARSAG",
#   "INDSATSER",
#   "UNDERRETERE",
#   "UNDERRET",
#   "AFFALDSOPR",
#   "AKTI",
#   "AKTP",
#   "VENTETIDGARANTI",
#   "MYNDIGHEDSKOM",
#   "AFSLUTSTATUS",
#   "BEBOSTAT",
#   "HERKAMS",
#   "OPHOLD2",
#   "OVERNAT",
#   "MLGRP",
#   "MND",
#   "SERVYD",
#   "HJEMBESOEG",
#   "TIMEUGE",
#   "KONAMS",
#   "OVERTRÆD",
#   "ANMSIGT",
#   "AFGØRELSE",
#   "STRAFLANG",
#   "VARTILBAGE",
#   "STRAFART",
#   "OVER",
#   "OVER1",
#   "STRAFART1",
#   "OVER2",
#   "STRAFART2",
#   "RECHEN",
#   "TIDLDOM",
#   "OVERNAT1",
#   "FDOMALD",
#   "LOVOV",
#   "AVFFS",
#   "FRISTRAF",
#   "ADOM",
#   "AFSLUT",
#   "BOPDK",
#   "AFSAVN",
#   "SPORG",
#   "SVAR",
#   "KOAL",
#   "SVAERHED1",
#   "INDKOMGRP",
#   "HFUIGANG",
#   "HFUDD2",
#   "INDIKATOR1",
#   "UDDSTAT",
#   "FORUDD1",
#   "FORIND",
#   "FORBESK",
#   "GRUNDSKOL",
#   "GRUNDBEL",
#   "DKMAT",
#   "IETYPE",
#   "STATUSVID",
#   "GRUNDKAR",
#   "FSTATUS",
#   "OMRÅDE1",
#   "KLASSE",
#   "SKTPE",
#   "ELEV",
#   "UDDDL",
#   "UDDFORM",
#   "HOMR",
#   "UDVEKSLING",
#   "OPVAR",
#   "INSTI",
#   "AFGAARG",
#   "AFGKLAS",
#   "AFGREG",
#   "STATUSTID",
#   "UDDANGROUP",
#   "STATUSAFG",
#   "ALDERLEV",
#   "STARTUD",
#   "STAT",
#   "STARTALD",
#   "FUDDOMR",
#   "TIDSPUNKTER",
#   "FORMEL",
#   "UFORMEL",
#   "UDDGRUND",
#   "EFTERVIR",
#   "ANSATTE",
#   "INSTTYP",
#   "KURSUS",
#   "HOEJ_UDD_FAM",
#   "AEKVI_FAM_INDKOMST",
#   "PERS_INDK",
#   "BOPLAND",
#   "FUI01",
#   "FUI08",
#   "LEVRTYP",
#   "VIDOMR",
#   "PERSTYP",
#   "FUI14",
#   "SEKVID",
#   "PERSONKAT",
#   "FAGET",
#   "DRIFT1",
#   "PCTBNP",
#   "UDGPOST",
#   "VIDENHOVED",
#   "SOCFORM",
#   "AARVAERK",
#   "OIN01",
#   "INNO",
#   "NYHEDSGRAD",
#   "OIN03",
#   "OIN02",
#   "INNBRANCHE",
#   "INNPRO",
#   "INNPROCES",
#   "INNSAM",
#   "RESSOMR",
#   "IPR1",
#   "IPR2",
#   "BRANCHEDB071019127",
#   "BRANCHEDB0710TIL127",
#   "FIRMSTR",
#   "BRANCHEDB0710",
#   "VIRKF1",
#   "FIRMAALDER",
#   "KONCERNSTOR",
#   "KONCERN",
#   "ARBSTRDK",
#   "STØRRELSE",
#   "VIRKSTR",
#   "BRANCHEDB0721",
#   "BESTPOST",
#   "VFORM",
#   "BESTMEDL",
#   "FIRMASTAT",
#   "VARIA",
#   "STARTAAR",
#   "VIRKTYP1",
#   "LEVTID",
#   "OMSÆTNING",
#   "BESK",
#   "BRANCHEREV2",
#   "EMNER",
#   "ANVEND",
#   "AKTIVI",
#   "REGNSKPOSTER",
#   "FINAKT",
#   "FINFORM",
#   "UDFALD",
#   "LAANEFIN",
#   "BELØB",
#   "OFFGRP",
#   "FONDSTYPE",
#   "BEVILLING2",
#   "VIRKE",
#   "MODTAG",
#   "MODTAGER",
#   "FAGOMR",
#   "FONDSMIDLER",
#   "UNDEROMRÅDE",
#   "LANDE",
#   "FIRMA",
#   "FUNKTIONER",
#   "JOBTYP",
#   "DESTINA",
#   "MOTIV",
#   "BETYD",
#   "FORTYP",
#   "PRODUKT",
#   "INVEST",
#   "FUI6",
#   "BEDRIFTSTAND",
#   "KVARTIL",
#   "BEDRIFTAARS",
#   "BRUGSTYPE",
#   "PRODGREN1",
#   "REGNP",
#   "REGNH",
#   "KAPIT",
#   "KORNART",
#   "AREALSTOR",
#   "BEDRIFT",
#   "AREAL1",
#   "UDBEDRIFT",
#   "BDFALDER",
#   "BEDRIFTSTR",
#   "FORP",
#   "BESKLAND",
#   "PRAETEK",
#   "UDALDER",
#   "AFGRØDE",
#   "AREALAFG",
#   "OMR2",
#   "SORT",
#   "TRE",
#   "KULT",
#   "DYR",
#   "BESAET",
#   "HUSDYRTYPE",
#   "DYRKAT",
#   "OPRIND",
#   "AK",
#   "STRUK",
#   "PROD",
#   "VÆKST",
#   "AREAL2",
#   "FODER2",
#   "VANDTY",
#   "FODER1",
#   "FODER",
#   "STOFTYPE",
#   "MÅLEENHED",
#   "PESTICIDGR",
#   "PESTICIDTYPE",
#   "BEVOKSNING",
#   "TRAESORT",
#   "FISKFAR",
#   "LAENG",
#   "TONNAGE",
#   "FANGST",
#   "LANDING1",
#   "FISK",
#   "FARLAENGD",
#   "ANLAEG",
#   "FISKSKAL",
#   "RÅSTOFTYPE",
#   "VARGR6",
#   "VARGR2",
#   "OMSTYPE",
#   "HOVEDGRP",
#   "MARKED1",
#   "STANDGRP",
#   "BYGFASE",
#   "BYGHERRE",
#   "AAR",
#   "BYGGESAG",
#   "ÅR",
#   "ARBART",
#   "AREALINT",
#   "AREALTYPE",
#   "OPVARM",
#   "TAGMAT",
#   "YDREMAT",
#   "HINDEKS",
#   "DINDEKS",
#   "BOLTYP",
#   "OVERNATF",
#   "NATION1",
#   "KAPACITET",
#   "SEG",
#   "CERT",
#   "FREMÅR",
#   "FREMMD",
#   "KAPMEDIE",
#   "FARVAND",
#   "TRANSMID",
#   "RAPINST",
#   "SEKKORNAT",
#   "SEKTOR2",
#   "RENTEFIX1",
#   "FORMAAL1",
#   "RENTE",
#   "RENTEREF",
#   "AFDRAG",
#   "RENTETYPE",
#   "EJENKATNAT",
#   "DISAGGBALPOST",
#   "AGGBALPOST",
#   "AKTTYP",
#   "EGENSEKTOR",
#   "BETALFRIST",
#   "SPECNAT",
#   "INSTITUTTYPE",
#   "NYUD",
#   "BALPOSTNAT1",
#   "INVESTFOND",
#   "HOVEDKAT",
#   "FORVALT",
#   "RISIKO",
#   "VARDIPAP",
#   "UDSTEDKAT",
#   "VIRKTYPNB",
#   "INVESTNAT",
#   "MARKVAERDI",
#   "MEDIER",
#   "OMSEKS",
#   "BEDØMMELSE",
#   "FORLØB",
#   "AARSAG",
#   "OPG",
#   "PAAFOR",
#   "BILTYPE",
#   "REGBIL",
#   "BILSEG",
#   "DRIV",
#   "BRUG",
#   "ENERGI",
#   "KM",
#   "KOEBMOENS",
#   "KOEBTYPE",
#   "BOL",
#   "RAADMOENS",
#   "BESTAND",
#   "SOMKOM",
#   "EGEN",
#   "BESTANDDEL",
#   "TVAEGT",
#   "AKSLER",
#   "SIDDE",
#   "TOG",
#   "VOGN2",
#   "SKIBTYPE",
#   "SKIBREG",
#   "BT",
#   "VEJSTR",
#   "VEJTYPE",
#   "TRANSPORT",
#   "BANE",
#   "FLAG",
#   "HAVN",
#   "LUFTHAVN",
#   "FLYVNING",
#   "BANEL",
#   "ROR",
#   "SDGSERVICE",
#   "BANES",
#   "FÆRGE",
#   "PASSAGER",
#   "PÅSTIG1",
#   "AFSTIG1",
#   "DESTI",
#   "REJSE",
#   "KØRART",
#   "TYPEVÆGT",
#   "BILALDER",
#   "TURKM",
#   "VOGN",
#   "LÆS",
#   "GODS",
#   "PÅREGION",
#   "AFREGION",
#   "LASTTYPE",
#   "REG",
#   "VOGN1",
#   "START1",
#   "SLUT1",
#   "PÅLAND",
#   "AFLAND",
#   "LAST",
#   "TRANSPORT1",
#   "UHELDA",
#   "UHELDSIT",
#   "BYLAND",
#   "HAST",
#   "KLOK",
#   "UGE",
#   "MODPART",
#   "TRANSINV",
#   "UHELD",
#   "SKADE",
#   "PERSART",
#   "GADEVEJ",
#   "IUDENFOR",
#   "SPIRIT",
#   "INDBLAND",
#   "KALDER",
#   "ALCO",
#   "INDBERET",
#   "SKADEDIAG",
#   "PKATEGORI",
#   "UTYPE",
#   "OMFANG",
#   "MUSEER",
#   "AFDLING",
#   "AKTIVITET",
#   "BESØGSTYPE",
#   "ALDERK",
#   "BESØG",
#   "GENRE",
#   "ADGANG",
#   "ZOOKAT",
#   "ZOO",
#   "BYGTYP",
#   "ANKAT",
#   "ARKIV",
#   "SAMLING",
#   "OPGOER1",
#   "MATER",
#   "MATYPELEK",
#   "UDLÅNSSTED",
#   "AFSTANDBIB",
#   "DIGITTJE",
#   "BIB2",
#   "KILD",
#   "PLACERING",
#   "LAESINTERVAL",
#   "UDGIVFREK",
#   "BOGER",
#   "GEOOMR",
#   "MEDIE",
#   "BOGTYPE",
#   "UDGAVE",
#   "SPROG",
#   "OVERSAT",
#   "BTYPE",
#   "OPLAG1",
#   "FORMAT",
#   "HOVEDGENRE",
#   "UDGIVELSESSPROG",
#   "RELATION",
#   "INSP",
#   "LAESFREK",
#   "SADER",
#   "BIOGRAF",
#   "BIO",
#   "NATION2",
#   "BIOSTOR",
#   "TYPMAL",
#   "URPRIM",
#   "FILMKAT",
#   "CENSUR",
#   "SPILLEUGE",
#   "KULTUR",
#   "LOKATION",
#   "FINANSTYPE",
#   "INDTTYPE",
#   "TEATTYP",
#   "PUBGRUP",
#   "SCENE",
#   "TEATER",
#   "MGK",
#   "ARBREG",
#   "OEKNOGL",
#   "KUNSTART",
#   "SOCIALSAM",
#   "MUSIKSAM",
#   "DISTRIB",
#   "RETTIGHED",
#   "MUSVÆRK",
#   "KONCERTARRANGØR",
#   "KONCERTSTØRRELSE",
#   "ARRANGEOR",
#   "BRANCHEKULT",
#   "UDDTYPE",
#   "CL_REGION",
#   "MESTER",
#   "IDRAET",
#   "MEDALJE",
#   "DICIPLIN",
#   "PRÆSTATION",
#   "RELATIV",
#   "RANG",
#   "KØNALDER",
#   "DELTAG1",
#   "TIDBRUG",
#   "ORGAN1",
#   "FORBACK",
#   "SPORTS",
#   "TILSKUER",
#   "IDRATAKT",
#   "STED",
#   "IDRFAC",
#   "ORGANISATION",
#   "SENANV",
#   "SENKOB",
#   "UDSTYR",
#   "ADFÆRD",
#   "OVERV",
#   "FORMAAL",
#   "FORHAND",
#   "BREDBAAND",
#   "BREDHAST",
#   "ANTALANDEL",
#   "PRIVAT",
#   "ANNONCERING",
#   "FORBRUG",
#   "TJEN1",
#   "KUNSTOMR",
#   "INDGRUND",
#   "VINDKOMST",
#   "KULTUREMNE",
#   "UDDINST",
#   "DIMMITEND",
#   "LEDTYP",
#   "INTNAT",
#   "EFFEKTER",
#   "KREATIVEERHVERV",
#   "FINANSART",
#   "STATSINSTITUITION",
#   "KUBSBELI",
#   "VIRKTYP2",
#   "LANDTYP",
#   "ARE1",
#   "BR19A2",
#   "ENERGI1",
#   "PVARMEKILDE",
#   "AARSFORBRUG",
#   "PRISDEFINITION",
#   "ENERGIENHED",
#   "TILANV",
#   "TILGANG",
#   "MULT",
#   "ANVEND1",
#   "EMTYPE8",
#   "OVERPOST",
#   "OPPRINCIP",
#   "ENERGIKILDE",
#   "ANVENDTYPE",
#   "UDLEDBRANCHE",
#   "UDLEDLAND",
#   "BRANCHEAFTRYK1",
#   "BEHANDLING",
#   "AFFFRAK",
#   "FARLIG",
#   "VANDTYP",
#   "INDKAT",
#   "UDL",
#   "MFORMAAL",
#   "KATEGORI",
#   "MILJOKAT",
#   "SKATTEART",
#   "BALPOST",
#   "OEKOSTATUS",
#   "VARTYP",
#   "MÆNGDE6",
#   "KUNDEGRP"
# )
#
#
#
#
#
# "TILKOMMUNE",
# "FRAKOMMUNE",


# Create the nested list structure
komgrp <- list(
  "1 Hovedstadskommuner" = list(
    "101 København" = "København",
    "147 Frederiksberg" = "Frederiksberg",
    "151 Ballerup" = "Ballerup",
    "153 Brøndby" = "Brøndby",
    "155 Dragør" = "Dragør",
    "157 Gentofte" = "Gentofte",
    "159 Gladsaxe" = "Gladsaxe",
    "161 Glostrup" = "Glostrup",
    "163 Herlev" = "Herlev",
    "165 Albertslund" = "Albertslund",
    "167 Hvidovre" = "Hvidovre",
    "169 Høje-Taastrup" = "Høje-Taastrup",
    "173 Lyngby-Taarbæk" = "Lyngby-Taarbæk",
    "175 Rødovre" = "Rødovre",
    "183 Ishøj" = "Ishøj",
    "185 Tårnby" = "Tårnby",
    "187 Vallensbæk" = "Vallensbæk",
    "190 Furesø" = "Furesø",
    "201 Allerød" = "Allerød",
    "223 Hørsholm" = "Hørsholm",
    "230 Rudersdal" = "Rudersdal",
    "240 Egedal" = "Egedal",
    "253 Greve" = "Greve",
    "269 Solrød" = "Solrød"
  ),

  "2 Storbykommuner" = list(
    "461 Odense" = "Odense",
    "751 Aarhus" = "Aarhus",
    "851 Aalborg" = "Aalborg"
  ),

  "3 Provinsbykommuner" = list(
    "217 Helsingør" = "Helsingør",
    "219 Hillerød" = "Hillerød",
    "259 Køge" = "Køge",
    "265 Roskilde" = "Roskilde",
    "330 Slagelse" = "Slagelse",
    "370 Næstved" = "Næstved",
    "561 Esbjerg" = "Esbjerg",
    "607 Fredericia" = "Fredericia",
    "615 Horsens" = "Horsens",
    "621 Kolding" = "Kolding",
    "630 Vejle" = "Vejle",
    "657 Herning" = "Herning",
    "661 Holstebro" = "Holstebro",
    "730 Randers" = "Randers",
    "740 Silkeborg" = "Silkeborg",
    "791 Viborg" = "Viborg"
  ),

  "4 Oplandskommuner" = list(
    "210 Fredensborg" = "Fredensborg",
    "250 Frederikssund" = "Frederikssund",
    "260 Halsnæs" = "Halsnæs",
    "270 Gribskov" = "Gribskov",
    "316 Holbæk" = "Holbæk",
    "320 Faxe" = "Faxe",
    "329 Ringsted" = "Ringsted",
    "336 Stevns" = "Stevns",
    "340 Sorø" = "Sorø",
    "350 Lejre" = "Lejre",
    "410 Middelfart" = "Middelfart",
    "420 Assens" = "Assens",
    "430 Faaborg-Midtfyn" = "Faaborg-Midtfyn",
    "440 Kerteminde" = "Kerteminde",
    "450 Nyborg" = "Nyborg",
    "480 Nordfyns" = "Nordfyns",
    "575 Vejen" = "Vejen",
    "706 Syddjurs" = "Syddjurs",
    "710 Favrskov" = "Favrskov",
    "727 Odder" = "Odder",
    "746 Skanderborg" = "Skanderborg",
    "756 Ikast-Brande" = "Ikast-Brande",
    "766 Hedensted" = "Hedensted",
    "840 Rebild" = "Rebild"
  ),

  "5 Landkommuner" = list(
    "306 Odsherred" = "Odsherred",
    "326 Kalundborg" = "Kalundborg",
    "360 Lolland" = "Lolland",
    "376 Guldborgsund" = "Guldborgsund",
    "390 Vordingborg" = "Vordingborg",
    "400 Bornholm" = "Bornholm",
    "479 Svendborg" = "Svendborg",
    "482 Langeland" = "Langeland",
    "492 Ærø" = "Ærø",
    "510 Haderslev" = "Haderslev",
    "530 Billund" = "Billund",
    "540 Sønderborg" = "Sønderborg",
    "550 Tønder" = "Tønder",
    "563 Fanø" = "Fanø",
    "573 Varde" = "Varde",
    "580 Aabenraa" = "Aabenraa",
    "665 Lemvig" = "Lemvig",
    "671 Struer" = "Struer",
    "707 Norddjurs" = "Norddjurs",
    "741 Samsø" = "Samsø",
    "760 Ringkøbing-Skjern" = "Ringkøbing-Skjern",
    "773 Morsø" = "Morsø",
    "779 Skive" = "Skive",
    "787 Thisted" = "Thisted",
    "810 Brønderslev" = "Brønderslev",
    "813 Frederikshavn" = "Frederikshavn",
    "820 Vesthimmerlands" = "Vesthimmerlands",
    "825 Læsø" = "Læsø",
    "846 Mariagerfjord" = "Mariagerfjord",
    "849 Jammerbugt" = "Jammerbugt",
    "860 Hjørring" = "Hjørring"
  )
)


kom_omraade <- c(
  "000 Hele landet",
  "1 Hovedstadskommuner",
  "2 Storbykommuner",
  "3 Provinsbykommuner",
  "4 Oplandskommuner",
  "5 Landkommuner",
  "101 København",
  "147 Frederiksberg",
  "155 Dragør",
  "185 Tårnby",
  "165 Albertslund",
  "151 Ballerup",
  "153 Brøndby",
  "157 Gentofte",
  "159 Gladsaxe",
  "161 Glostrup",
  "163 Herlev",
  "167 Hvidovre",
  "169 Høje-Taastrup",
  "183 Ishøj",
  "173 Lyngby-Taarbæk",
  "175 Rødovre",
  "187 Vallensbæk",
  "201 Allerød",
  "240 Egedal",
  "210 Fredensborg",
  "250 Frederikssund",
  "190 Furesø",
  "270 Gribskov",
  "260 Halsnæs",
  "217 Helsingør",
  "219 Hillerød",
  "223 Hørsholm",
  "230 Rudersdal",
  "400 Bornholm",
  "411 Christiansø",
  "253 Greve",
  "259 Køge",
  "350 Lejre",
  "265 Roskilde",
  "269 Solrød",
  "320 Faxe",
  "376 Guldborgsund",
  "316 Holbæk",
  "326 Kalundborg",
  "360 Lolland",
  "370 Næstved",
  "306 Odsherred",
  "329 Ringsted",
  "330 Slagelse",
  "340 Sorø",
  "336 Stevns",
  "390 Vordingborg",
  "420 Assens",
  "430 Faaborg-Midtfyn",
  "440 Kerteminde",
  "482 Langeland",
  "410 Middelfart",
  "480 Nordfyns",
  "450 Nyborg",
  "461 Odense",
  "479 Svendborg",
  "492 Ærø",
  "530 Billund",
  "561 Esbjerg",
  "563 Fanø",
  "607 Fredericia",
  "510 Haderslev",
  "621 Kolding",
  "540 Sønderborg",
  "550 Tønder",
  "573 Varde",
  "575 Vejen",
  "630 Vejle",
  "580 Aabenraa",
  "710 Favrskov",
  "766 Hedensted",
  "615 Horsens",
  "707 Norddjurs",
  "727 Odder",
  "730 Randers",
  "741 Samsø",
  "740 Silkeborg",
  "746 Skanderborg",
  "706 Syddjurs",
  "751 Aarhus",
  "657 Herning",
  "661 Holstebro",
  "756 Ikast-Brande",
  "665 Lemvig",
  "760 Ringkøbing-Skjern",
  "779 Skive",
  "671 Struer",
  "791 Viborg",
  "810 Brønderslev",
  "813 Frederikshavn",
  "860 Hjørring",
  "849 Jammerbugt",
  "825 Læsø",
  "846 Mariagerfjord",
  "773 Morsø",
  "840 Rebild",
  "787 Thisted",
  "820 Vesthimmerlands",
  "851 Aalborg"
)


geographic_vectors <- list(
  "komgrp" = komgrp,
  "kom_omraade" = kom_omraade
)
